### ISSUE TITLE
[Story] Initiate documentation

### ISSUE THREAD

**Issue by KinaUna** [KinaUna/Examplium#14]
Epic: #10 

### Description

As a learning project documentation and a version control system is needed from the start to keep track of things.

### Tasks

- [x] Create GitHub repository (this repository).
- [x] Add Documentation directory and index to organize documentation.
- [x] Add first milestone in GitHub: Startup initiation.
- [x] Add GitHub Project for "Startup - Initiation".
- [x] Add labels for "documentation", "first steps" to track initial work.
- [x] Add labels and templates for "epic", "story", and "task" to help organize projects and issues.

**Comment by KinaUna** [comment]
This was created in retrospect for documentation, all task have been completed already.
