### ISSUE TITLE
[Story] Create business plan

### ISSUE THREAD

**Issue by KinaUna** [KinaUna/Examplium#15]
Epic: #10 

### Description
A startup needs a business plan at some point. 

Create a draft business plan for the startup.

### Tasks

- [x] Add business plan document in "Documents/Business/Startup/" directory.
- [x] Fill in basis information: Purpose of the startup, target market, value proposition.
- [x] Update documentation index, directory index if needed.

**Comment by KinaUna** [comment]
Added business plan document.

Filled in basic plan information.

Updated the index pages.
