### ISSUE TITLE
[Story] Create First product plan

### ISSUE THREAD

**Issue by KinaUna** [KinaUna/Examplium#16]
Epic: #10 

### Description
As a founder I want to have a plan for the first product, so I can clearly see what is being built, what needs to be done, and what has been done.
 
### Tasks

- [x] Create directory for the product plan and add the plan document.
- [x] Add Concept Development page.
- [x] Add Competitive Analysis page.
- [X] Add Market Research page.
- [x] Add MVP/Prototype Development page.
- [x] Add project in GitHub for prototype development.
- [x] Add milestone in GitHub for prototype.

**Comment by KinaUna** [comment]
Added documents, project and milestone.
