### ISSUE TITLE
[Story] Add Log in

### ISSUE THREAD

**Issue by KinaUna** [KinaUna/Examplium#19]
Epic: #17 

### Description
As a user I want to be able to log in to be able to manage my content.

### Tasks

- [ ] Use the default implementation of Identity Server/Duende.
- [ ] Configure database settings using localDb with Entity Framework.
- [ ] Update the ApplicationUser model.
- [ ] Update the database.
- [ ] Test login.

**Comment by KinaUna** [comment]
The plan changed, login has been implemented with Duende Identity Server instead.
