### ISSUE TITLE
[Story] Add Sign up

### ISSUE THREAD

**Issue by KinaUna** [KinaUna/Examplium#21]
Epic: #17 

### Description
As a user I want to be able to sign up and create and account so I can start managing content.

### Tasks

- [ ] Use the default implementation of Identity Server/Duende.
- [ ] Configure email service for verification.
- [ ] Test sign up functionality.

**Comment by KinaUna** [comment]
Fixed typo in title.

**Comment by KinaUna** [comment]
The plan changed, sign up/registration has been implemented with Duende Identity Server instead.
