### ISSUE TITLE
[Story] Delete account

### ISSUE THREAD

**Issue by KinaUna** [KinaUna/Examplium#22]
Epic: #17 

### Description
As a user I want to be able to delete my account, to ensure I don't have any information saved if I no longer want to use this product.

### Tasks

- [ ] Add function to delete all  of a user's content.
- [ ] Add function to delete account.
- [ ] Add page with delete account function.
- [ ] Test delete account function.

**Comment by KinaUna** [comment]
The plan changed, delete account will be implemented with Duende Identity Server instead.
