### ISSUE TITLE
[Story] Add confirmation email

### ISSUE THREAD

**Issue by KinaUna** [KinaUna/Examplium#23]
Epic: #17 

### Description
As a user I want to confirm that the email address I use for my account to belongs to me, so that no one else can use my email address for an account.

### Tasks

- [ ] Add email service.
- [ ] Add send confirmation email function.
- [ ] Add confirmation function.

**Comment by KinaUna** [comment]
The plan changed, confirmation email will be implemented with Duende Identity Server instead.
