### ISSUE TITLE
[Story] Add add note

### ISSUE THREAD

**Issue by KinaUna** [KinaUna/Examplium#26]
Epic: #18 

### Description
As a user I want to be able to write notes and save them, so I can view them later.

### Tasks

- [x] Create note model.
- [x] Create note service.
- [x] Create add note function.
- [x] Create add note page.

**Comment by KinaUna** [comment]
Created add notes as part of the notes feature implementation, see:
https://github.com/KinaUna/Examplium/tree/master/Documentation/Code/Notes
