### ISSUE TITLE
[Story] Add Initial Identity Server Administrator 

### ISSUE THREAD

**Issue by KinaUna** [KinaUna/Examplium#46]
Epic: #45 

### Description
Add initial administrator account to Identity Server.

### Tasks

- [x] Add initial administrator email and password to secrets.
- [x] Add Admin role.
- [x] Update IdentityServerInitialization.cs to add the administrator account.

**Comment by KinaUna** [comment]
Added code for for roles and adding the initial administrator account.
See https://github.com/KinaUna/Examplium/blob/master/Documentation/Code/IdentityServer/09-Add-Administration.md
