### ISSUE TITLE
[Story] Add Identity Server Reset Configuration

### ISSUE THREAD

**Issue by KinaUna** [KinaUna/Examplium#49]
Epic: #45 

### Description
Add a page to reset the database for Clients, ApiResources, IdentityResources, and ApiScopes.

### Tasks

- [x] Add Reset Configuration page
- [x] Add Reset Clients function
- [x] Add Reset ApiResources function
- [x] Add Reset IdentityResources function
- [x] Add Reset ApiScopes function
- [x] Add reset all function.

**Comment by KinaUna** [comment]
Completed the reset configuration pages, for details see:
https://github.com/KinaUna/Examplium/blob/master/Documentation/Code/IdentityServer/09-Add-Administration.md
